# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            За Декана
tagline:          'За лучший мехмат'
description:      'Кампания за достойного декана механико-математического факультета'
url:              https://zadekana.ru/
